### ISSUE TITLE
Unexpect effect invocation.

### ISSUE THREAD

**Issue by zhaoyao91** [solidui/solid#422]
**IMPORTANT: If you have a question or an idea for a new feature use Github Discussions instead**

**Describe the bug**

When I have a state of an array of items with some fields, I use an effect to watch some of these fieds. But when I update some other fields, the effect rerun again, which may waste computation resources.

**To Reproduce**

see this [demo](https://playground.solidjs.com/#NobwRAlgJmBcYHYICcBsALAhgRgGYA5cBTABgE5VUAvVMgGwA8BbAR3zABowA7TJouGCaYI3TmAAuATwAOA+BIDODcYoD2AV2QBjeZCYy1yCQAIQJ5EW5QiyEwF8TuZGqYmA5OrrQAtACtFAHoAdyIAI3cAbgAdbggDI1NzbUtMCSIAZQgAc146DhMUojTMiRKCopKAUVxibQkCmRcoDV0HJxc3TzVvKH9FKNjY3A1ueog1bhMAYU1udOQACgBKM1iTQsnFU2Bt8pNFIgkMsvSAXRMAXkLU9JOSxZBMZGRYE1BMWGx7AqfYACYfmZPgBmexnezLIZTG7FdI1OoSRYrK4APjWMI2e3SADpnsgcbgjFVMNp0IsGGiMRsaZtuF4iDi6GpshS8VDMQ4ORtIdCsUcACrxIiaJEoy7okDrGmHY6nIiLJpqFq6AA8mG4UlRi2xRCpUs5WPleJewGwZxxYSuJn+-2lPOW3IcBWwJDdHOllgkWim3A0dDosXs0Ms1lsyNWEpMqtmowWJkCqIKUDU2g0-HmOOyRyqdCIGYkACEpABJKCLdyYGQydyO6FgcFAA)

**Expected behavior**

when timouet triggers, there is no new console outputs.

**Comment by zhaoyao91** [comment]
Another question, by design, is it ok to use forEach on state array? I mean, if we push new item into it, will `forEach` trigger rerun of effect, by design?

**Comment by ryansolid** [comment]
To allow iteration of object keys I retrigger the parent when new properties are added or removed. Similarly, arrays always notify the parent when the indexes change. Generally this is ok, as if you initialize state with the correct shape (ie.. b as null) it won't re-execute. And if even if re-executed once it won't do so again. The only place this is problematic is if you are constantly adding a bunch of unknown properties.

So to answer your question if you were iterating or reading that array anywhere it would rerun when new items are added (or pushed from `produce`). Keep in mind it will re-run against all entries. The reason we have a special `mapArray` and `<For>` helper is so that we don't re-map everything every time. But the default behavior is to re-run everything.

**Comment by zhaoyao91** [comment]
Precise anwser and sensible design! thanks
